allowedDeprecatedVersions:
  eslint: "8.57.x"
  "@humanwhocodes/config-array": "0.13.x"
  "@humanwhocodes/object-schema": "2.0.x"
  glob: "7.2.x"
  inflight: "1.0.x"
  rimraf: "3.0.x"
  "semver-diff": "5.0.x"
peerDependencyRules:
  allowedVersions:
    "@typescript-eslint/eslint-plugin": "7.18.x"
