import type { McpServerTool } from '../../server/types.js'
import statsTool from './queries/stats.js'



const fieldValues = [
  'customer.id',
  'customer.email',
  'customer.group_name',
  'line_items.code',
  'line_items.discount',
  'line_items.id',
  'line_items.item_id',
  'line_items.options_amount',
  'line_items.quantity',
  'line_items.tax_amount',
  'line_items.tax_rate',
  'line_items.total_amount',
  'line_items.unit_amount',
  'line_items.options.id',
  'line_items.options.quantity',
  'line_items.options.total_amount',
  'line_items.options.unit_amount',
  'market.id',
  'market.number',
  'order.adjustment_amount',
  'order.adjustment_tax_amount',
  'order.adjustment_taxable_amount',
  'order.discount_amount',
  'order.duty_amount',
  'order.gift_card_code',
  'order.gift_card_amount',
  'order.id',
  'order.line_item_options_count',
  'order.number',
  'order.payment_method_amount',
  'order.payment_method_tax_amount',
  'order.payment_method_taxable_amount',
  'order.reference',
  'order.reference_origin',
  'order.shipments_count',
  'order.shipping_amount',
  'order.shipping_taxable_amount',
  'order.skus_count',
  'order.subtotal_amount',
  'order.subtotal_tax_amount',
  'order.subtotal_taxable_amount',
  'order.total_amount',
  'order.total_amount_with_taxes',
  'order.total_tax_amount',
  'order.total_taxable_amount',
  'order.seconds_in_draft',
  'order.seconds_in_approved',
  'order.seconds_in_placed',
  'order.refunds_total_amount_with_taxes',
  'order.total_amount_with_taxes_net_of_refunds',
  'refunds.id',
  'refunds.amount',
  'refunds.number',
  'shipments.id',
  'shipments.number',
  'shipments.reference',
  'shipments.reference_origin',
  'shipments.seconds_in_picking',
  'shipments.seconds_in_ready_to_ship',
  'shipments.stock_location.id',
  'shipments.stock_location.reference',
  'shipments.stock_location.reference_origin',
  'shipments.shipping_method.id',
  'shipments.shipping_method.reference',
  'shipments.shipping_method.reference_origin',
  'shipments.shipping_category.id',
  'shipments.shipping_category.reference',
  'shipments.shipping_category.reference_origin',
  'resource_errors.code',
  'resource_errors.id',
  'resource_errors.message'
] as const



const ordersStats: McpServerTool = statsTool('orders', { fieldValues })


export default ordersStats
